name: CD
on: 
  push:
    tags: 
    - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: mymindstorm/setup-emsdk@v14
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - name: Build init
      run: just build-web-init
    - name: Build
      run: just build-web
