name: CD

on: 
  push:
    tags: 
    - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Emscripten sdk
      uses: mymindstorm/setup-emsdk@v14
    - name: Install Just
      uses: extractions/setup-just@v1
    - name: Build init
      run: just build-web-init
    - name: Build
      run: just build-web
    - name: Rename html file
      run: mv build-web/dst/colbox.html build-web/dst/index.html
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build-web/dst
        branch: gh-pages
