name: CD
on: 
  push:
    tags: 
    - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: mymindstorm/setup-emsdk@v14
    - uses: actions/checkout@v3
    - uses: m3y/rust-just-action@v1
      with:
        command: build-web-init
        file: ./Justfile
    - uses: m3y/rust-just-action@v1
      with:
        command: build-web
        file: ./Justfile
